package by.alesnax.qanda.command.client;

public enum CommandName {
	ADD_QUESTION,
	CHANGE_LANGUAGE,
	CLEAN_QUESTION_FORM,
	CHANGE_USER_INFO,
	CHANGE_USER_LANGUAGE,
	CHANGE_PASSWORD,
	FIND_BEST_ANSWERS,
	FIND_BEST_QUESTIONS,
	FIND_BEST_USERS,
	FOLLOW_USER,
	DELETE_POST,
	GO_TO_AUTHORIZATION_PAGE,
	GO_TO_CATEGORY,
	GO_TO_FIRST_PAGE,
	GO_TO_FRIENDS,
	GO_TO_MAIN_PAGE,
	GO_TO_MY_NEWS,
	GO_TO_PASSWORD_RECOVERY,
	GO_TO_POST_COMPLAINT,
	GO_TO_POST_CORRECTION,
	GO_TO_PROFILE,
	GO_TO_EDIT_PROFILE,
	GO_TO_QUEST_CATEGORIES,
	GO_TO_QUESTION,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_REPOSTS,
	LOG_OUT,
	RATE_POST,
	REGISTER_NEW_USER,
	REMOVE_FOLLOWING_USER,
	SEARCH_ANSWER_QUESTION,
	USER_AUTHORIZATION,
	UPLOAD_FILE




}
