package by.alesnax.qanda.command.client;

public enum CommandName {
	ADD_QUESTION,
	CHANGE_LANGUAGE,
	CLEAN_QUESTION_FORM,

	FIND_BEST_ANSWERS,
	FIND_BEST_QUESTIONS,
	FIND_BEST_USERS,
	GO_TO_AUTHORIZATION_PAGE,
	GO_TO_CATEGORY,
	GO_TO_FIRST_PAGE,
	GO_TO_FRIENDS,
	GO_TO_MAIN_PAGE,
	GO_TO_MY_NEWS,
	GO_TO_PROFILE,
	GO_TO_QUEST_CATEGORIES,
	GO_TO_REGISTRATION_PAGE,
	LOG_OUT,
	REGISTER_NEW_USER,
	SEARCH_ANSWER_QUESTION,
	USER_AUTHORIZATION,




}
